#!/bin/bash
# chkconfig: 2345 20 80
# description: Spinel authenticating gateway 

# Source function library.
. /etc/init.d/functions


SCRIPT=/usr/local/bin/spinel
RUNAS=nginx

PIDFILE=/var/run/spinel.pid
LOGFILE=/var/log/spinel.log


start() {
    # code to start app comes here 
    # example: daemon program_name &
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
      echo 'Service already running' >&2
      return 1
    fi
    echo 'Starting service…' >&2
    local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
    su -s "/bin/bash" -c "$CMD" $RUNAS > "$PIDFILE"
    echo 'Service started' >&2
}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
      echo 'Service not running' >&2
      return 1
    fi
    echo 'Stopping service…' >&2
    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo 'Service stopped' >&2
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0 
