secret: GFE7py2bavDyMvtgOGR/Jm4H3BcoxSDcboNRgZ3i8NI= 
expires: 24
listen: localhost:9999
ad:
  host: localhost
  port: 389
  dsn: OU=foo,dc=bar,dc=bim,dc=bam
cidrs:
  - 10.0.0.0/8
    #  - 127.0.0.1/32
